### ISSUE TITLE
Dashboard information in not loaded 

### ISSUE THREAD

**Issue by lavs023** [T-M-D/NLS-Collection#1]
Hi, I have a problem with the information in the dashboard, when I import the dashboard don't information is loaded. I configure the filter and create a new input in the Nagios Log server, and ran the command  **bash setup-linux.sh -s butan.uniandes.edu.co -p 5544 -f "/usr/local/nagios/var/nagios.log" -t nagios_core**  in the NagiosXI server. Is necessary create a input?

Thank you

![screenshot from 2017-09-04 16-18-37](https://user-images.githubusercontent.com/31634246/30038672-e229476e-918c-11e7-9fcc-bac8f39ab977.png)

**Comment by box293** [comment]
You don't need to create an input, the logs are received via the `Syslog (default)` input, only the filter you created is required. You should remove that input you created.

After Saving and Applying Config, the dashboard will return data once some has been received. If you have a healthy Nagios server then you may not actually be receiving any logs (until something happens).

You can go to a blank dashboard and perform this query:
```
program:nagios_core
```

This will show any logs that have been received by your Nagios Log Server. If you don't receive any logs then the following KB article should help troubleshoot your issue:

https://support.nagios.com/kb/article/nagios-log-server-logs-not-searchable-or-not-coming-in.html

**Comment by lavs023** [comment]
Hi, thanks for you support, I removed the input and ran **netstat -tupan | grep syslog** in the NagiosXi server without output, restarted the rsyslog service and ran **netstat -tupan | grep syslog**  without output again, finally restarted the NagiosXI server and ran the netstat command with a correct output:

[root@nlserver~]# netstat -taupn | grep 5544
tcp        0      0 157.253.77.41:53652         157.253.77.72:5544          ESTABLISHED 2054/rsyslogd  

And finally the dasboard load sucessyfull, thanks a lot.
